using System.Collections.Generic;

namespace Playground.Dto
{
    /// <summary>
    /// Data transfer object of an item.
    /// </summary>
    public class ItemDto : ResourceBase
    {
        /// <summary>
        /// Identifier of the item. Autogenerated.
        /// </summary>
        public string Id { get; set; }

        /// <summary>
        /// Item's name. Mandatory.
        /// </summary>
        public string Name { get; set; }

        /// <summary>
        /// Item's description. Optional.
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// Item's owner. Optional.
        /// </summary>
        public string Owner { get; set; }

        /// <summary>
        /// Set of tags
        /// </summary>
        public List<string> Tags { get; set; }
    }
}
